services:
  - type: web
    name: peblo-ai-notes
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        value: /tmp/peblo.sqlite
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
